import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/**/*.{vue,js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Poppins', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                primary: 'rgb(var(--primary))',
                'primary-inverse': 'rgb(var(--primary-inverse))',
                'primary-hover': 'rgb(var(--primary-hover))',
                'primary-active-color': 'rgb(var(--primary-active-color))',
                'primary-highlight': 'rgb(var(--primary)/var(--primary-highlight-opacity))',
                'primary-highlight-inverse': 'rgb(var(--primary-highlight-inverse))',
                'primary-highlight-hover': 'rgb(var(--primary)/var(--primary-highlight-hover-opacity))',
                'primary-50': 'rgb(var(--primary-50))',
                'primary-100': 'rgb(var(--primary-100))',
                'primary-200': 'rgb(var(--primary-200))',
                'primary-300': 'rgb(var(--primary-300))',
                'primary-400': 'rgb(var(--primary-400))',
                'primary-500': 'rgb(var(--primary-500))',
                'primary-600': 'rgb(var(--primary-600))',
                'primary-700': 'rgb(var(--primary-700))',
                'primary-800': 'rgb(var(--primary-800))',
                'primary-900': 'rgb(var(--primary-900))',
                'primary-950': 'rgb(var(--primary-950))',
                'surface-0': 'rgb(var(--surface-0))',
                'surface-50': 'rgb(var(--surface-50))',
                'surface-100': 'rgb(var(--surface-100))',
                'surface-200': 'rgb(var(--surface-200))',
                'surface-300': 'rgb(var(--surface-300))',
                'surface-400': 'rgb(var(--surface-400))',
                'surface-500': 'rgb(var(--surface-500))',
                'surface-600': 'rgb(var(--surface-600))',
                'surface-700': 'rgb(var(--surface-700))',
                'surface-800': 'rgb(var(--surface-800))',
                'surface-900': 'rgb(var(--surface-900))',
                'surface-950': 'rgb(var(--surface-950))',
                gray: {
                    50: '#F9FAFB',
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#111827',
                    950: '#030712',
                },
                success: {
                    50: '#F0FDF4',
                    100: '#DCFCE7',
                    200: '#BBF7D0',
                    300: '#86EFAC',
                    400: '#4ADE80',
                    500: '#22C55E',
                    600: '#16A34A',
                    700: '#15803D',
                    800: '#166534',
                    900: '#14532D',
                    950: '#052E16',
                },
                info: {
                    50: '#F0F9FF',
                    100: '#E0F2FE',
                    200: '#BAE6FD',
                    300: '#7DD3FC',
                    400: '#38BDF8',
                    500: '#0EA5E9',
                    600: '#0284C7',
                    700: '#0369A1',
                    800: '#075985',
                    900: '#0C4A6E',
                    950: '#082F49',
                },
                warning: {
                    50: '#FEFCE8',
                    100: '#FEF9C3',
                    200: '#FEF08A',
                    300: '#FDE047',
                    400: '#FACC15',
                    500: '#EAB308',
                    600: '#CA8A04',
                    700: '#A16207',
                    800: '#854D0E',
                    900: '#713F12',
                    950: '#422006',
                },
                error: {
                    50: '#FEF2F2',
                    100: '#FEE2E2',
                    200: '#FECACA',
                    300: '#FCA5A5',
                    400: '#F87171',
                    500: '#EF4444',
                    600: '#DC2626',
                    700: '#B91C1C',
                    800: '#991B1B',
                    900: '#7F1D1D',
                    950: '#450A0A',
                },
                indigo: '#4E5FBB',
                cyan: '#00BCD4',
                teal: '#009688',
                orange: '#FF9800',
                cerisa_red: '#E91E63',
                violet: '#9C27B0',
                purple: '#673AB7',
            },
            boxShadow: {
                'input': '0 1px 2px 0px rgba(12, 17, 29, 0.05)',
                'focus': '0px 0px 0px 3px #C7EBC9',
                'dropdown': '0px 8px 16px -4px rgba(12, 17, 29, 0.08)',
                'dialog': '0 12px 24px -4px rgba(12, 17, 29, 0.10)',
                'card': '0px 4px 30px 0px #F3F4F6',
                'primary-button': 'inset 2px 2px 4px #67C16B, 0 2px 2px #2E7D32',
                'gray-button': 'inset 2px 2px 4px #D1D5DB, 0 2px 2px #D1D5DB',
                // 'toast': '0 4px 20px 0 rgba(12, 17, 29, 0.08)',
                // 'table': '0 2px 8px 0 rgba(12, 17, 29, 0.05)',
            },
            fontSize: {
                xxxs: ['8px', '8px'],
                xxs: ['10px', '12px'],
                xs: ['12px', '16px'],
                sm: ['14px', '20px'],
                base: ['16px', '24px'],
                lg: ['20px', '28px'],
                xl: ['24px', '32px'],
                xxl: ['30px', '42px'],
            },
            screens: {
                'sm': '320px',
                'smd': '430px',
                'md': '768px',
                'lg': '1024px',
                'xl': '1280px',
                '2xl': '1536px',
                '3xl': '1792px',
            },
            typography: ({ theme }) => ({
                DEFAULT: {
                    css: {
                        '--tw-prose-paragraphs': theme('colors.gray[700]'),
                        '--tw-prose-headings': theme('colors.gray[950]'),
                        '--tw-prose-counters': theme('colors.gray[300]'),
                        '--tw-prose-bold': theme('colors.gray[950]'),
                        '--tw-prose-bullets': theme('colors.gray[500]'),
                        h1: {
                            fontSize: '30px',
                            lineHeight: '42px'
                        },
                        h2: {
                            fontSize: '24px',
                            lineHeight: '32px'
                        },
                        h3: {
                            fontSize: '20px',
                            lineHeight: '28px'
                        },
                        p: {
                            fontSize: '16px',
                            lineHeight: '24px'
                        },
                        a: {
                            color: theme('colors.primary'),
                            textDecoration: 'underline',
                            '&:hover': {
                                color: theme('colors.primary-hover'),
                            }
                        },
                        maxWidth: '100ch',
                    }
                }
            }),
        },
    },
    plugins: [
        forms,
        typography,
    ],
}
